### ISSUE TITLE
Demo does not working

### ISSUE THREAD

**Issue by kiennt** [graphql-python/django-graphene-example#1] opened 2015-11-17 15:38 UTC
I tried [demo with this query](http://swapi.graphene-python.org/graphiql?query=%23%20Welcome%20to%20GraphiQL%0A%23%0A%23%20GraphiQL%20is%20an%20in-browser%20IDE%20for%20writing%2C%20validating%2C%20and%0A%23%20testing%20GraphQL%20queries.%0A%23%0A%23%20Type%20queries%20into%20this%20side%20of%20the%20screen%2C%20and%20you%20will%0A%23%20see%20intelligent%20typeaheads%20aware%20of%20the%20current%20GraphQL%20type%20schema%20and%0A%23%20live%20syntax%20and%20validation%20errors%20highlighted%20within%20the%20text.%0A%23%0A%23%20To%20bring%20up%20the%20auto-complete%20at%20any%20point%2C%20just%20press%20Ctrl-Space.%0A%23%0A%23%20Press%20the%20run%20button%20above%2C%20or%20Cmd-Enter%20to%20execute%20the%20query%2C%20and%20the%20result%0A%23%20will%20appear%20in%20the%20pane%20to%20the%20right.%0A%0A%7B%0A%20%20allFilms%28%29%20%7B%0A%20%20%09edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%20%0A%20%20%7D%0A%7D%0A)

```
{
  allFilms() {
    edges {
      node {
        id
      }
    } 
  }
}
```

But I got error

```
{
  "errors": [
    {
      "message": "type object 'Film' has no attribute 'get_object_type'",
      "locations": [
        {
          "line": 16,
          "column": 3
        }
      ]
    }
  ],
  "data": {
    "allFilms": null
  }
}
```

**Comment by syrusakbary** [comment] 2015-11-18 01:31
Hi @kiennt!
Thanks for pointing this out. This was caused by a problem in `graphene` package, that was solved by this commit: https://github.com/graphql-python/graphene/commit/266dd5efe089e92d235802166471b1fbbf7f58d6

The example will upgrade soon to `graphene` `v0.4.0.1` that have a fix for that.

**Comment by syrusakbary** [comment] 2015-11-19 01:48
This is now fixed.
You can query:

``` graphql
{
  allFilms {
    edges {
      node {
        id
      }
    } 
  }
}
```

**Closed as completed** 2015-11-19 01:48 UTC
